### ISSUE TITLE
[HTML] create index.html

### ISSUE THREAD

**Issue by Jayone12** [Jayone12/pig-dice-game#1]
## Tasks

- [ ] Create a 2 player status window
- [ ] Create each button(roll, hold, new)
- [ ] Create 'Help'
- [ ] write style sheet

**Comment by Naveenravi07** [comment]
still available?
